/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mcs9222.hms.Boundary;

import com.mcs9222.hms.Controller.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hz957
 */
public class SysWindow extends javax.swing.JFrame {

    private ServiceCheckinController checkin;
    private ServiceCheckoutController scc;
    private ServiceServiceController ssc;
    private ProfilePersonalController ppc;
    private ProfileAgencyController pac;
    private ReportSelectController rsc;
    private ReportGenerateController rgc;
    private ReportExportController rec;
    private ReservationAddController rac;
    private ReservationModifyController rmc;

    /**
     * Creates new form SysWindow
     */
    public SysWindow() {
        initComponents();
        setLocationRelativeTo(null);
        rec = new ReportExportController(reportTable, reportSummary);
        checkin = new ServiceCheckinController(serviceNameTextField, serviceIDTextField, serviceCCardTextField,
                serviceCardTypeCombo, serviceExpiryTextField, serviceCheckinTable);
        scc = new ServiceCheckoutController(serviceCheckoutNameTextField, serviceCheckoutTable);
        ssc = new ServiceServiceController(serviceRoomNoTextField, serviceServiceTable);
        ppc = new ProfilePersonalController(profileNameTextField, profilePersonalTable);
        pac = new ProfileAgencyController(profileAgencyTextField, profileAgencyTable);
        rsc = new ReportSelectController(reportTable, reportTypesList, reportSummary);
        reportTable.setModel(new DefaultTableModel());
        rgc = new ReportGenerateController(reportStartDateTextField, reportEndDateTextField, reportTypesList);
        rac = new ReservationAddController(this.reservationRoomTypeComboBox, this.reservationStartDateTextField, this.reservationEndDateTextField, this.reservationResultsTable);
        rmc = new ReservationModifyController(this.reservationPhoneTextField, this.reservationOrderTable);
    }

    public void setPermissionByRole(String name, String role) {
        userLabel.setText(role + ": " + name);
        // by default, all functional tabs are unavailable
        mainTabbedPane.setEnabledAt(0, false);
        mainTabbedPane.setEnabledAt(1, false);
        mainTabbedPane.setEnabledAt(2, false);
        mainTabbedPane.setEnabledAt(3, false);

        reservationTabbedPane.setVisible(false);
        serviceTabbedPane.setVisible(false);
        profileTabbedPane.setVisible(false);
        reportTable.setVisible(false);
        if (role.equals("Manager")) {
            mainTabbedPane.setSelectedIndex(3);
            mainTabbedPane.setEnabledAt(3, true);
            DefaultListModel listModel = new DefaultListModel();
            listModel.addElement("Checkin Report");
            listModel.addElement("Checkout Report");
            listModel.addElement("Revenue Summary");
            listModel.addElement("Booking Activity");
            reportTypesList.setModel(listModel);

        } else if (role.equals("Receptionist")) {
            mainTabbedPane.setEnabledAt(0, true);
            mainTabbedPane.setEnabledAt(1, true);
            mainTabbedPane.setEnabledAt(2, true);
            mainTabbedPane.setEnabledAt(3, true);
            reservationTabbedPane.setVisible(true);
            serviceTabbedPane.setVisible(true);
            profileTabbedPane.setVisible(true);
            DefaultListModel listModel = new DefaultListModel();
            listModel.addElement("Expected Arrivals");
            reportTypesList.setModel(listModel);
            ppc.setTableModelByDefault();
            pac.setTableModelByDefault();

        } else if (role.equals("Service Staff")) {
            mainTabbedPane.setEnabledAt(2, true);
            mainTabbedPane.setSelectedIndex(2);
            serviceTabbedPane.setVisible(true);
            serviceTabbedPane.setEnabledAt(0, false);
            serviceTabbedPane.setEnabledAt(1, false);
            serviceTabbedPane.setSelectedIndex(2);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField14 = new javax.swing.JTextField();
        mainTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        reservationTabbedPane = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reservationRoomTypeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        reservationStartDateTextField = new ObservingTextField();
        jLabel5 = new javax.swing.JLabel();
        reservationEndDateTextField = new ObservingTextField();
        reservationRoomSearchButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        reservationResultsTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        reservationPhoneTextField = new javax.swing.JTextField();
        reservationOrderSearchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reservationOrderTable = new javax.swing.JTable();
        reservationDeleteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        profileTabbedPane = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        profileNameTextField = new javax.swing.JTextField();
        profileSearchButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        profilePersonalTable = new javax.swing.JTable();
        profileDeleteButton = new javax.swing.JButton();
        profileAddButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        profileAgencyTextField = new javax.swing.JTextField();
        profileAgencySearchButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        profileAgencyTable = new javax.swing.JTable();
        profileAgencyAddButton = new javax.swing.JButton();
        profileAgnecyDeleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        serviceTabbedPane = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        serviceNameTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        serviceIDTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        serviceCCardTextField = new javax.swing.JTextField();
        serviceCardTypeCombo = new javax.swing.JComboBox();
        serviceCheckinButton = new javax.swing.JButton();
        serviceExpiryTextField = new ObservingTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceCheckinTable = new javax.swing.JTable();
        serviceSearchButton = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        serviceCheckoutNameTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        serviceCheckoutTable = new javax.swing.JTable();
        serviceCheckoutButton = new javax.swing.JButton();
        serviceCheckoutSearchButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        serviceRoomNoTextField = new javax.swing.JTextField();
        serviceServiceSearchButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        serviceServiceTable = new javax.swing.JTable();
        serviceServiceAddButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        reportTypesList = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        reportStartDateTextField = new ObservingTextField();
        jLabel16 = new javax.swing.JLabel();
        reportEndDateTextField = new ObservingTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        reportTable = new javax.swing.JTable();
        reportViewButton = new javax.swing.JButton();
        reportExportButton = new javax.swing.JButton();
        reportSummary = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTextField14.setText("jTextField14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 380));
        setResizable(false);

        jLabel1.setText("Room Type");

        reservationRoomTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Double", "TwinDouble", "HollywoodTwin", "Parlour", "Suite" }));

        jLabel2.setText("Start Date");

        reservationStartDateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationStartDateTextFieldMouseClicked(evt);
            }
        });

        jLabel5.setText("End Date");

        reservationEndDateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationEndDateTextFieldMouseClicked(evt);
            }
        });

        reservationRoomSearchButton.setText("Search");
        reservationRoomSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationRoomSearchButtonActionPerformed(evt);
            }
        });

        reservationResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Type", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reservationResultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservationResultsTableMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(reservationResultsTable);
        reservationResultsTable.getColumnModel().getColumn(0).setResizable(false);
        reservationResultsTable.getColumnModel().getColumn(1).setResizable(false);
        reservationResultsTable.getColumnModel().getColumn(2).setResizable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reservationRoomTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reservationStartDateTextField)
                            .addComponent(reservationEndDateTextField)))
                    .addComponent(reservationRoomSearchButton))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(reservationRoomTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(reservationStartDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(reservationEndDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(reservationRoomSearchButton)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        reservationTabbedPane.addTab("Add", jPanel5);

        jLabel6.setText("Name");

        reservationOrderSearchButton.setText("Search");
        reservationOrderSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationOrderSearchButtonActionPerformed(evt);
            }
        });

        reservationOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        reservationOrderTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                reservationOrderTableFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(reservationOrderTable);

        reservationDeleteButton.setText("Delete");
        reservationDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservationPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reservationOrderSearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(reservationDeleteButton)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(reservationPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reservationOrderSearchButton)
                    .addComponent(reservationDeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        reservationTabbedPane.addTab("Modify", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservationTabbedPane)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reservationTabbedPane)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Reservation", jPanel1);

        jLabel7.setText("Name");

        profileSearchButton.setText("Search");
        profileSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileSearchButtonActionPerformed(evt);
            }
        });

        profilePersonalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(profilePersonalTable);

        profileDeleteButton.setText("Delete");
        profileDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileDeleteButtonActionPerformed(evt);
            }
        });

        profileAddButton.setText("Add");
        profileAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profileSearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(profileAddButton)
                        .addGap(18, 18, 18)
                        .addComponent(profileDeleteButton)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(profileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileSearchButton)
                    .addComponent(profileDeleteButton)
                    .addComponent(profileAddButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        profileTabbedPane.addTab("Personal", jPanel11);

        jLabel8.setText("Agency Name");

        profileAgencySearchButton.setText("Search");
        profileAgencySearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileAgencySearchButtonActionPerformed(evt);
            }
        });

        profileAgencyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(profileAgencyTable);

        profileAgencyAddButton.setText("Add");
        profileAgencyAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileAgencyAddButtonActionPerformed(evt);
            }
        });

        profileAgnecyDeleteButton.setText("Delete");
        profileAgnecyDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileAgnecyDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profileAgencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profileAgencySearchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profileAgencyAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profileAgnecyDeleteButton)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(profileAgencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileAgencySearchButton)
                    .addComponent(profileAgencyAddButton)
                    .addComponent(profileAgnecyDeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        profileTabbedPane.addTab("Agency", jPanel12);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileTabbedPane)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileTabbedPane)
                .addContainerGap())
        );

        mainTabbedPane.addTab("Profile", jPanel2);

        jLabel10.setText("Name");

        jLabel11.setText("ID");

        serviceIDTextField.setEnabled(false);

        jLabel12.setText("Credit Card");

        serviceCCardTextField.setEnabled(false);

        serviceCardTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Master" }));
        serviceCardTypeCombo.setEnabled(false);

        serviceCheckinButton.setText("Checkin");
        serviceCheckinButton.setEnabled(false);
        serviceCheckinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceCheckinButtonActionPerformed(evt);
            }
        });

        serviceExpiryTextField.setEnabled(false);
        serviceExpiryTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceExpiryTextFieldMouseClicked(evt);
            }
        });

        jLabel3.setText("Expiry");

        serviceCheckinTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Expected Checkin", "Room Number", "Room Type", "Expected Checkout"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(serviceCheckinTable);
        serviceCheckinTable.getColumnModel().getColumn(0).setResizable(false);
        serviceCheckinTable.getColumnModel().getColumn(4).setResizable(false);

        serviceSearchButton.setText("Search");
        serviceSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(27, 27, 27)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(serviceIDTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(serviceNameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(serviceCCardTextField)))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(61, 61, 61)
                            .addComponent(serviceExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(serviceCardTypeCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(serviceSearchButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(serviceCheckinButton)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(serviceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(serviceIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(serviceCCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(serviceCardTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serviceExpiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(serviceCheckinButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(serviceSearchButton)
                        .addGap(27, 27, 27))))
        );

        serviceTabbedPane.addTab("Checkin", jPanel8);

        jLabel14.setText("Name");

        serviceCheckoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room Number", "Checkin Date", "Checkout Date", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(serviceCheckoutTable);
        serviceCheckoutTable.getColumnModel().getColumn(0).setResizable(false);
        serviceCheckoutTable.getColumnModel().getColumn(1).setResizable(false);
        serviceCheckoutTable.getColumnModel().getColumn(2).setResizable(false);
        serviceCheckoutTable.getColumnModel().getColumn(3).setResizable(false);

        serviceCheckoutButton.setText("Checkout");
        serviceCheckoutButton.setEnabled(false);
        serviceCheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceCheckoutButtonActionPerformed(evt);
            }
        });

        serviceCheckoutSearchButton.setText("Search");
        serviceCheckoutSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceCheckoutSearchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(serviceCheckoutNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(serviceCheckoutSearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(serviceCheckoutButton)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(serviceCheckoutNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceCheckoutButton)
                    .addComponent(serviceCheckoutSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        serviceTabbedPane.addTab("Checkout", jPanel9);

        jLabel15.setText("Room Number");

        serviceServiceSearchButton.setText("Search");
        serviceServiceSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceServiceSearchButtonActionPerformed(evt);
            }
        });

        serviceServiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(serviceServiceTable);
        serviceServiceTable.getColumnModel().getColumn(0).setResizable(false);
        serviceServiceTable.getColumnModel().getColumn(1).setResizable(false);
        serviceServiceTable.getColumnModel().getColumn(2).setResizable(false);

        serviceServiceAddButton.setText("Add");
        serviceServiceAddButton.setEnabled(false);
        serviceServiceAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceServiceAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(serviceRoomNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 647, Short.MAX_VALUE)
                .addComponent(serviceServiceSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(serviceServiceAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(serviceRoomNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serviceServiceSearchButton)
                    .addComponent(serviceServiceAddButton))
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(55, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(16, Short.MAX_VALUE)))
        );

        serviceTabbedPane.addTab("Service", jPanel10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serviceTabbedPane)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(serviceTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Service", jPanel3);

        reportTypesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        reportTypesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reportTypesListValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(reportTypesList);

        jLabel9.setText("Start Date");

        reportStartDateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportStartDateTextFieldMouseClicked(evt);
            }
        });

        jLabel16.setText("End Date");

        reportEndDateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportEndDateTextFieldMouseClicked(evt);
            }
        });

        reportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(reportTable);

        reportViewButton.setText("View");
        reportViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportViewButtonActionPerformed(evt);
            }
        });

        reportExportButton.setText("Export");
        reportExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportExportButtonActionPerformed(evt);
            }
        });

        reportSummary.setText("Total checkin:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(reportSummary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reportViewButton)
                        .addGap(18, 18, 18)
                        .addComponent(reportExportButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(reportStartDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(reportEndDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(reportStartDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(reportEndDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportSummary)
                            .addComponent(reportViewButton)
                            .addComponent(reportExportButton))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        mainTabbedPane.addTab("Report", jPanel4);

        userLabel.setText("User");

        jLabel4.setText("Hotel Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainTabbedPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservationRoomSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationRoomSearchButtonActionPerformed
        try {
            // TODO add your handling code here:
            rac.searchRoom();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Please enter start date and end date");
        }
    }//GEN-LAST:event_reservationRoomSearchButtonActionPerformed

    private void serviceExpiryTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceExpiryTextFieldMouseClicked
        addDatePicker((ObservingTextField) serviceExpiryTextField);
    }//GEN-LAST:event_serviceExpiryTextFieldMouseClicked

    private void reservationStartDateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationStartDateTextFieldMouseClicked
        addDatePicker((ObservingTextField) reservationStartDateTextField);
    }//GEN-LAST:event_reservationStartDateTextFieldMouseClicked

    private void reservationEndDateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationEndDateTextFieldMouseClicked
        addDatePicker((ObservingTextField) reservationEndDateTextField);
    }//GEN-LAST:event_reservationEndDateTextFieldMouseClicked

    private void reportStartDateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportStartDateTextFieldMouseClicked
        addDatePicker((ObservingTextField) reportStartDateTextField);
    }//GEN-LAST:event_reportStartDateTextFieldMouseClicked

    private void reportEndDateTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportEndDateTextFieldMouseClicked
        addDatePicker((ObservingTextField) reportEndDateTextField);
    }//GEN-LAST:event_reportEndDateTextFieldMouseClicked

    private void reservationOrderSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationOrderSearchButtonActionPerformed
        // TODO add your handling code here:
        rmc.searchOrder();
    }//GEN-LAST:event_reservationOrderSearchButtonActionPerformed

    private void reservationDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationDeleteButtonActionPerformed
        rmc.deleteRoom();

    }//GEN-LAST:event_reservationDeleteButtonActionPerformed

    private void profileSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileSearchButtonActionPerformed
        ppc.setTableModelByName();
    }//GEN-LAST:event_profileSearchButtonActionPerformed

    private void profileAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileAddButtonActionPerformed
        ppc.doAdd();
    }//GEN-LAST:event_profileAddButtonActionPerformed

    private void profileDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileDeleteButtonActionPerformed
        ppc.doDelete();
    }//GEN-LAST:event_profileDeleteButtonActionPerformed

    private void profileAgencySearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileAgencySearchButtonActionPerformed
        pac.setTableModelByName();
    }//GEN-LAST:event_profileAgencySearchButtonActionPerformed

    private void profileAgencyAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileAgencyAddButtonActionPerformed
        pac.doAdd();
    }//GEN-LAST:event_profileAgencyAddButtonActionPerformed

    private void profileAgnecyDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileAgnecyDeleteButtonActionPerformed
        pac.doDelete();
    }//GEN-LAST:event_profileAgnecyDeleteButtonActionPerformed

    private void serviceCheckinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCheckinButtonActionPerformed
        boolean bResults = checkin.doCheckin();
        if (bResults == false) {
            JOptionPane.showMessageDialog(this, "Please specify all customer information");
        }
    }//GEN-LAST:event_serviceCheckinButtonActionPerformed

    private void serviceCheckoutSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCheckoutSearchButtonActionPerformed
        scc.doSearch();
        if (serviceCheckoutTable.getRowCount() > 0) {
            serviceCheckoutButton.setEnabled(true);
        } else {
            serviceCheckoutButton.setEnabled(false);
            JOptionPane.showMessageDialog(this, "No Results");
        }
    }//GEN-LAST:event_serviceCheckoutSearchButtonActionPerformed

    private void serviceCheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceCheckoutButtonActionPerformed
        scc.doCheckout();
    }//GEN-LAST:event_serviceCheckoutButtonActionPerformed

    private void serviceServiceSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceServiceSearchButtonActionPerformed
        if (ssc.doSearch() == true) {
            serviceServiceAddButton.setEnabled(true);
        } else {
            serviceServiceAddButton.setEnabled(false);
            JOptionPane.showMessageDialog(this, "No Results");
        }
    }//GEN-LAST:event_serviceServiceSearchButtonActionPerformed

    private void serviceServiceAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceServiceAddButtonActionPerformed
        ssc.doAdd();
    }//GEN-LAST:event_serviceServiceAddButtonActionPerformed

    private void reportTypesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reportTypesListValueChanged
        rsc.doChangeType();
        rgc.doChangeSummary(reportSummary);
    }//GEN-LAST:event_reportTypesListValueChanged

    private void reportViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportViewButtonActionPerformed

        rgc.doRetrieveTableData(reportTable, reportSummary);

    }//GEN-LAST:event_reportViewButtonActionPerformed

    private void reportExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportExportButtonActionPerformed

        rec.saveFile();

    }//GEN-LAST:event_reportExportButtonActionPerformed

    private void reservationResultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservationResultsTableMouseClicked
        int selectedRow = reservationResultsTable.getSelectedRow();
        String roomNo = rac.getRoomNo(selectedRow);

        Date startDate = null;
        Date endDate = null;
        try {
            startDate = new SimpleDateFormat("dd/MM/yy").parse(this.reservationStartDateTextField.getText());
            endDate = new SimpleDateFormat("dd/MM/yy").parse(this.reservationEndDateTextField.getText());
        } catch (ParseException ex) {
            Logger.getLogger(SysWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        CustomerInfoBookingWindow cibw = new CustomerInfoBookingWindow(roomNo, startDate, endDate, rac, selectedRow);
        cibw.setVisible(true);
    }//GEN-LAST:event_reservationResultsTableMouseClicked

    private void serviceSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceSearchButtonActionPerformed
        if (checkin.doSearch() == false) {
            JOptionPane.showMessageDialog(this, "No Results");
        } else {
            serviceCheckinButton.setEnabled(true);
        }
    }//GEN-LAST:event_serviceSearchButtonActionPerformed

    private void reservationOrderTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reservationOrderTableFocusLost

        rmc.modifyOrder();

    }//GEN-LAST:event_reservationOrderTableFocusLost

    private void addDatePicker(ObservingTextField otf) {
        final Locale locale = Locale.UK;
        DatePicker dp = new DatePicker(otf, locale);
        dp.start(otf);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SysWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SysWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SysWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SysWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               JFrame.setDefaultLookAndFeelDecorated(true);   
        try { 
          UIManager.setLookAndFeel("org.jvnet.substance.skin.SubstanceBusinessLookAndFeel"); 
  //          UIManager.setLookAndFeel(new SubstanceBusinessBlueSteelLookAndFeel());   
        } catch (Exception e) {   
            System.out.println("Substance Raven Graphite failed to initialize");   
        }   
                new SysWindow().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton profileAddButton;
    private javax.swing.JButton profileAgencyAddButton;
    private javax.swing.JButton profileAgencySearchButton;
    private javax.swing.JTable profileAgencyTable;
    private javax.swing.JTextField profileAgencyTextField;
    private javax.swing.JButton profileAgnecyDeleteButton;
    private javax.swing.JButton profileDeleteButton;
    private javax.swing.JTextField profileNameTextField;
    private javax.swing.JTable profilePersonalTable;
    private javax.swing.JButton profileSearchButton;
    private javax.swing.JTabbedPane profileTabbedPane;
    private javax.swing.JTextField reportEndDateTextField;
    private javax.swing.JButton reportExportButton;
    private javax.swing.JTextField reportStartDateTextField;
    private javax.swing.JLabel reportSummary;
    private javax.swing.JTable reportTable;
    private javax.swing.JList reportTypesList;
    private javax.swing.JButton reportViewButton;
    private javax.swing.JButton reservationDeleteButton;
    private javax.swing.JTextField reservationEndDateTextField;
    private javax.swing.JButton reservationOrderSearchButton;
    private javax.swing.JTable reservationOrderTable;
    private javax.swing.JTextField reservationPhoneTextField;
    private javax.swing.JTable reservationResultsTable;
    private javax.swing.JButton reservationRoomSearchButton;
    private javax.swing.JComboBox reservationRoomTypeComboBox;
    private javax.swing.JTextField reservationStartDateTextField;
    private javax.swing.JTabbedPane reservationTabbedPane;
    private javax.swing.JTextField serviceCCardTextField;
    private javax.swing.JComboBox serviceCardTypeCombo;
    private javax.swing.JButton serviceCheckinButton;
    private javax.swing.JTable serviceCheckinTable;
    private javax.swing.JButton serviceCheckoutButton;
    private javax.swing.JTextField serviceCheckoutNameTextField;
    private javax.swing.JButton serviceCheckoutSearchButton;
    private javax.swing.JTable serviceCheckoutTable;
    private javax.swing.JTextField serviceExpiryTextField;
    private javax.swing.JTextField serviceIDTextField;
    private javax.swing.JTextField serviceNameTextField;
    private javax.swing.JTextField serviceRoomNoTextField;
    private javax.swing.JButton serviceSearchButton;
    private javax.swing.JButton serviceServiceAddButton;
    private javax.swing.JButton serviceServiceSearchButton;
    private javax.swing.JTable serviceServiceTable;
    private javax.swing.JTabbedPane serviceTabbedPane;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
